/*
 * Copyright (c), ACCES I/O Products, Inc.
 * All rights reserved.
 * 
 * Contributor(s):
 * Zach Perez, zach.perez@accesio.com
 * 
 * PERMISSION TO USE, COPY, MODIFY, AND/OR DISTRIBUTE THIS SOFTWARE FOR ANY
 * PURPOSE WITH OR WITHOUT FEE IS HEREBY GRANTED, PROVIDED THAT THE ABOVE
 * COPYRIGHT NOTICE AND THIS PERMISSION NOTICE APPEAR IN ALL COPIES.
 * 
 * THIS SOFTWARE IS PROVIDED BY ACCES I/O AND CONTRIBUTORS "AS IS" AND ANY
 * EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL ACCES I/O AND CONTRIBUTORS BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
#ifndef ACCESIO_LINUX_IDS_H
#define ACCESIO_LINUX_IDS_H

// don't include directly, this is included in module.h

// VENDOR ID
#define ACCESIO_USB_VID 0x1605

// DEVICE ID'S
#define ACCESIO_USB_DA12_8A_REV_A  0xC001
#define ACCESIO_USB_DA12_8A        0xC002
#define ACCESIO_USB_DA12_8E        0xC003

// DEVICE ID'S BEFORE FIRMWARE
#define ACCESIO_NOFW_USB_DIO_32         0x0001
#define ACCESIO_NOFW_USB_DIO_32I        0x0004
#define ACCESIO_NOFW_USB_DIO_24         0x0005
#define ACCESIO_NOFW_USB_DIO_48         0x0002
#define ACCESIO_NOFW_USB_DIO_96         0x0003
#define ACCESIO_NOFW_USB_DIO_24_CTR6    0x0006
#define ACCESIO_NOFW_USB_DI_16A_REV_A1  0x0008
#define ACCESIO_NOFW_USB_DO_16A_REV_A1  0x0009
#define ACCESIO_NOFW_USB_DI_16A_REV_A2  0x000A
#define ACCESIO_NOFW_USB_DIO_16H        0x000C
#define ACCESIO_NOFW_USB_DI_16A         0x000D
#define ACCESIO_NOFW_USB_DO_16A         0x000E
#define ACCESIO_NOFW_USB_DIO_16A        0x000F
#define ACCESIO_NOFW_USB_IIRO_16        0x0010
#define ACCESIO_NOFW_USB_II_16          0x0011
#define ACCESIO_NOFW_USB_RO_16          0x0012
#define ACCESIO_NOFW_USB_IIRO_8         0x0014
#define ACCESIO_NOFW_USB_II_8           0x0015
#define ACCESIO_NOFW_USB_IIRO_4         0x0016
#define ACCESIO_NOFW_USB_IDIO_16        0x0018
#define ACCESIO_NOFW_USB_II_16_OEM      0x0019
#define ACCESIO_NOFW_USB_IDO_16         0x001A
#define ACCESIO_NOFW_USB_IDIO_8         0x001C
#define ACCESIO_NOFW_USB_II_8_OEM       0x001D
#define ACCESIO_NOFW_USB_IDIO_4         0x001E
#define ACCESIO_NOFW_USB_II_4_OEM       0x001F
#define ACCESIO_NOFW_USB_CTR_15         0x0020
#define ACCESIO_NOFW_USB_IIRO4_2SM      0x0030
#define ACCESIO_NOFW_USB_IIRO4_COM      0x0031
#define ACCESIO_NOFW_USB_DIO_16_RO_8    0x0032
#define ACCESIO_NOFW_USB_DIO_48_DO_24   0x003C
#define ACCESIO_NOFW_USB_DIO_24_DO_12   0x003D
#define ACCESIO_NOFW_USB_DO_24          0x003E
#define ACCESIO_NOFW_PICO_DIO_16_RO_8   0x0033
#define ACCESIO_NOFW_USBP_II8_IDO_4A    0x0036
#define ACCESIO_NOFW_PICO_II8_IDO_4A    0x0037
#define ACCESIO_NOFW_USB_AI16_16A       0x0040
#define ACCESIO_NOFW_USB_AI16_16E       0x0041
#define ACCESIO_NOFW_USB_AI12_16A       0x0042
#define ACCESIO_NOFW_USB_AI12_16        0x0043
#define ACCESIO_NOFW_USB_AI12_16E       0x0044
#define ACCESIO_NOFW_USB_AI16_64MA      0x0045
#define ACCESIO_NOFW_USB_AI16_64ME      0x0046
#define ACCESIO_NOFW_USB_AI12_64MA      0x0047
#define ACCESIO_NOFW_USB_AI12_64M       0x0048
#define ACCESIO_NOFW_USB_AI12_64ME      0x0049
#define ACCESIO_NOFW_USB_AI16_32A       0x004A
#define ACCESIO_NOFW_USB_AI16_32E       0x004B
#define ACCESIO_NOFW_USB_AI12_32A       0x004C
#define ACCESIO_NOFW_USB_AI12_32        0x004D
#define ACCESIO_NOFW_USB_AI12_32E       0x004E
#define ACCESIO_NOFW_USB_AI16_64A       0x004F
#define ACCESIO_NOFW_USB_AI16_64E       0x0050
#define ACCESIO_NOFW_USB_AI12_64A       0x0051
#define ACCESIO_NOFW_USB_AI12_64        0x0052
#define ACCESIO_NOFW_USB_AI12_64E       0x0053
#define ACCESIO_NOFW_USB_AI16_96A       0x0054
#define ACCESIO_NOFW_USB_AI16_96E       0x0055
#define ACCESIO_NOFW_USB_AI12_96A       0x0056
#define ACCESIO_NOFW_USB_AI12_96        0x0057
#define ACCESIO_NOFW_USB_AI12_96E       0x0058
#define ACCESIO_NOFW_USB_AI16_128A      0x0059
#define ACCESIO_NOFW_USB_AI16_128E      0x005A
#define ACCESIO_NOFW_USB_AI12_128A      0x005B
#define ACCESIO_NOFW_USB_AI12_128       0x005C
#define ACCESIO_NOFW_USB_AI12_128E      0x005D
#define ACCESIO_NOFW_USB_AO_ARB1        0x0068
#define ACCESIO_NOFW_USB_AO16_16A       0x0070
#define ACCESIO_NOFW_USB_AO16_16        0x0071
#define ACCESIO_NOFW_USB_AO16_12A       0x0072
#define ACCESIO_NOFW_USB_AO16_12        0x0073
#define ACCESIO_NOFW_USB_AO16_8A        0x0074
#define ACCESIO_NOFW_USB_AO16_8         0x0075
#define ACCESIO_NOFW_USB_AO16_4A        0x0076
#define ACCESIO_NOFW_USB_AO16_4         0x0077
#define ACCESIO_NOFW_USB_AO12_16A       0x0078
#define ACCESIO_NOFW_USB_AO12_16        0x0079
#define ACCESIO_NOFW_USB_AO12_12A       0x007A
#define ACCESIO_NOFW_USB_AO12_12        0x007B
#define ACCESIO_NOFW_USB_AO12_8A        0x007C
#define ACCESIO_NOFW_USB_AO12_8         0x007D
#define ACCESIO_NOFW_USB_AO12_4A        0x007E
#define ACCESIO_NOFW_USB_AO12_4         0x007F
#define ACCESIO_NOFW_USB_AIO16_16A      0x0140
#define ACCESIO_NOFW_USB_AIO16_16E      0x0141
#define ACCESIO_NOFW_USB_AIO12_16A      0x0142
#define ACCESIO_NOFW_USB_AIO12_16       0x0143
#define ACCESIO_NOFW_USB_AIO12_16E      0x0144
#define ACCESIO_NOFW_USB_AIO16_64MA     0x0145
#define ACCESIO_NOFW_USB_AIO16_64ME     0x0146
#define ACCESIO_NOFW_USB_AIO12_64MA     0x0147
#define ACCESIO_NOFW_USB_AIO12_64M      0x0148
#define ACCESIO_NOFW_USB_AIO12_64ME     0x0149
#define ACCESIO_NOFW_USB_AIO16_32A      0x014A
#define ACCESIO_NOFW_USB_AIO16_32E      0x014B
#define ACCESIO_NOFW_USB_AIO12_32A      0x014C
#define ACCESIO_NOFW_USB_AIO12_32       0x014D
#define ACCESIO_NOFW_USB_AIO12_32E      0x014E
#define ACCESIO_NOFW_USB_AIO16_64A      0x014F
#define ACCESIO_NOFW_USB_AIO16_64E      0x0150
#define ACCESIO_NOFW_USB_AIO12_64A      0x0151
#define ACCESIO_NOFW_USB_AIO12_64       0x0152
#define ACCESIO_NOFW_USB_AIO12_64E      0x0153
#define ACCESIO_NOFW_USB_AIO16_96A      0x0154
#define ACCESIO_NOFW_USB_AIO16_96E      0x0155
#define ACCESIO_NOFW_USB_AIO12_96A      0x0156
#define ACCESIO_NOFW_USB_AIO12_96       0x0157
#define ACCESIO_NOFW_USB_AIO12_96E      0x0158
#define ACCESIO_NOFW_USB_AIO16_128A     0x0159
#define ACCESIO_NOFW_USB_AIO16_128E     0x015A
#define ACCESIO_NOFW_USB_AIO12_128A     0x015B
#define ACCESIO_NOFW_USB_AIO12_128      0x015C
#define ACCESIO_NOFW_USB_AIO12_128E     0x015D
#define ACCESIO_NOFW_USB_AI16_2A        0x0180

// DEVICE ID'S AFTER FIRMWARE
#define ACCESIO_USB_DIO_32         0x8001
#define ACCESIO_USB_DIO_32I        0x8004
#define ACCESIO_USB_DIO_24         0x8005
#define ACCESIO_USB_DIO_48         0x8002
#define ACCESIO_USB_DIO_96         0x8003
#define ACCESIO_USB_DIO_24_CTR6    0x8006
#define ACCESIO_USB_DI_16A_REV_A1  0x8008
#define ACCESIO_USB_DO_16A_REV_A1  0x8009
#define ACCESIO_USB_DI_16A_REV_A2  0x800A
#define ACCESIO_USB_DIO_16H        0x800C
#define ACCESIO_USB_DI_16A         0x800D
#define ACCESIO_USB_DO_16A         0x800E
#define ACCESIO_USB_DIO_16A        0x800F
#define ACCESIO_USB_IIRO_16        0x8010
#define ACCESIO_USB_II_16          0x8011
#define ACCESIO_USB_RO_16          0x8012
#define ACCESIO_USB_IIRO_8         0x8014
#define ACCESIO_USB_II_8           0x8015
#define ACCESIO_USB_IIRO_4         0x8016
#define ACCESIO_USB_IDIO_16        0x8018
#define ACCESIO_USB_II_16_OEM      0x8019
#define ACCESIO_USB_IDO_16         0x801A
#define ACCESIO_USB_IDIO_8         0x801C
#define ACCESIO_USB_II_8_OEM       0x801D
#define ACCESIO_USB_IDIO_4         0x801E
#define ACCESIO_USB_II_4_OEM       0x801F
#define ACCESIO_USB_CTR_15         0x8020
#define ACCESIO_USB_IIRO4_2SM      0x8030
#define ACCESIO_USB_IIRO4_COM      0x8031
#define ACCESIO_USB_DIO_16_RO_8    0x8032
#define ACCESIO_USB_DIO_48_DO_24   0x803C
#define ACCESIO_USB_DIO_24_DO_12   0x803D
#define ACCESIO_USB_DO_24          0x803E
#define ACCESIO_PICO_DIO_16_RO_8   0x8033
#define ACCESIO_USBP_II8_IDO_4A    0x8036
#define ACCESIO_PICO_II8_IDO_4A    0x8037
#define ACCESIO_USB_AI16_16A       0x8040
#define ACCESIO_USB_AI16_16E       0x8041
#define ACCESIO_USB_AI12_16A       0x8042
#define ACCESIO_USB_AI12_16        0x8043
#define ACCESIO_USB_AI12_16E       0x8044
#define ACCESIO_USB_AI16_64MA      0x8045
#define ACCESIO_USB_AI16_64ME      0x8046
#define ACCESIO_USB_AI12_64MA      0x8047
#define ACCESIO_USB_AI12_64M       0x8048
#define ACCESIO_USB_AI12_64ME      0x8049
#define ACCESIO_USB_AI16_32A       0x804A
#define ACCESIO_USB_AI16_32E       0x804B
#define ACCESIO_USB_AI12_32A       0x804C
#define ACCESIO_USB_AI12_32        0x804D
#define ACCESIO_USB_AI12_32E       0x804E
#define ACCESIO_USB_AI16_64A       0x804F
#define ACCESIO_USB_AI16_64E       0x8050
#define ACCESIO_USB_AI12_64A       0x8051
#define ACCESIO_USB_AI12_64        0x8052
#define ACCESIO_USB_AI12_64E       0x8053
#define ACCESIO_USB_AI16_96A       0x8054
#define ACCESIO_USB_AI16_96E       0x8055
#define ACCESIO_USB_AI12_96A       0x8056
#define ACCESIO_USB_AI12_96        0x8057
#define ACCESIO_USB_AI12_96E       0x8058
#define ACCESIO_USB_AI16_128A      0x8059
#define ACCESIO_USB_AI16_128E      0x805A
#define ACCESIO_USB_AI12_128A      0x805B
#define ACCESIO_USB_AI12_128       0x805C
#define ACCESIO_USB_AI12_128E      0x805D
#define ACCESIO_USB_AO_ARB1        0x8068
#define ACCESIO_USB_AO16_16A       0x8070
#define ACCESIO_USB_AO16_16        0x8071
#define ACCESIO_USB_AO16_12A       0x8072
#define ACCESIO_USB_AO16_12        0x8073
#define ACCESIO_USB_AO16_8A        0x8074
#define ACCESIO_USB_AO16_8         0x8075
#define ACCESIO_USB_AO16_4A        0x8076
#define ACCESIO_USB_AO16_4         0x8077
#define ACCESIO_USB_AO12_16A       0x8078
#define ACCESIO_USB_AO12_16        0x8079
#define ACCESIO_USB_AO12_12A       0x807A
#define ACCESIO_USB_AO12_12        0x807B
#define ACCESIO_USB_AO12_8A        0x807C
#define ACCESIO_USB_AO12_8         0x807D
#define ACCESIO_USB_AO12_4A        0x807E
#define ACCESIO_USB_AO12_4         0x807F
#define ACCESIO_USB_AIO16_16A      0x8140
#define ACCESIO_USB_AIO16_16E      0x8141
#define ACCESIO_USB_AIO12_16A      0x8142
#define ACCESIO_USB_AIO12_16       0x8143
#define ACCESIO_USB_AIO12_16E      0x8144
#define ACCESIO_USB_AIO16_64MA     0x8145
#define ACCESIO_USB_AIO16_64ME     0x8146
#define ACCESIO_USB_AIO12_64MA     0x8147
#define ACCESIO_USB_AIO12_64M      0x8148
#define ACCESIO_USB_AIO12_64ME     0x8149
#define ACCESIO_USB_AIO16_32A      0x814A
#define ACCESIO_USB_AIO16_32E      0x814B
#define ACCESIO_USB_AIO12_32A      0x814C
#define ACCESIO_USB_AIO12_32       0x814D
#define ACCESIO_USB_AIO12_32E      0x814E
#define ACCESIO_USB_AIO16_64A      0x814F
#define ACCESIO_USB_AIO16_64E      0x8150
#define ACCESIO_USB_AIO12_64A      0x8151
#define ACCESIO_USB_AIO12_64       0x8152
#define ACCESIO_USB_AIO12_64E      0x8153
#define ACCESIO_USB_AIO16_96A      0x8154
#define ACCESIO_USB_AIO16_96E      0x8155
#define ACCESIO_USB_AIO12_96A      0x8156
#define ACCESIO_USB_AIO12_96       0x8157
#define ACCESIO_USB_AIO12_96E      0x8158
#define ACCESIO_USB_AIO16_128A     0x8159
#define ACCESIO_USB_AIO16_128E     0x815A
#define ACCESIO_USB_AIO12_128A     0x815B
#define ACCESIO_USB_AIO12_128      0x815C
#define ACCESIO_USB_AIO12_128E     0x815D
#define ACCESIO_USB_AI16_2A        0x8180

// WHEN ADDING NEW USB DEVICE
// 1.) ADD NEW USB DEVICE PID (NON-FW AND W/ FW)
// 2.) INCREASE CARD COUNT
// 3.) ADD TO TABLE accesio_usb_ids
// 4.) ADD TO NAME FUNCTION get_name_from_id
// 5.) ADD TO COUNTER FUNCTION get_counter_from_id

#define ACCESIO_USB_CARD_COUNT 128 // actual = 117

// USB PID table
static struct usb_device_id accesio_usb_ids[] = {
    // DEVICE ID'S
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DA12_8A_REV_A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DA12_8A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DA12_8E) },
    // DEVICE ID'S BEFORE FIRMWARE
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_32) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_32I) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_24) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_48) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_96) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_24_CTR6) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DI_16A_REV_A1) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DO_16A_REV_A1) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DI_16A_REV_A2) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_16H) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DI_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DO_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_IIRO_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_II_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_RO_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_IIRO_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_II_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_IIRO_4) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_IDIO_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_II_16_OEM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_IDO_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_IDIO_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_II_8_OEM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_IDIO_4) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_II_4_OEM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_CTR_15) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_IIRO4_2SM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_IIRO4_COM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_16_RO_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_48_DO_24) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DIO_24_DO_12) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_DO_24) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_PICO_DIO_16_RO_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USBP_II8_IDO_4A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_PICO_II8_IDO_4A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_16E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_16E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_64MA) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_64ME) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_64MA) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_64M) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_64ME) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_32A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_32E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_32A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_32) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_32E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_64A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_64E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_64A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_64) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_64E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_96A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_96E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_96A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_96) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_96E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_128A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_128E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_128A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_128) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI12_128E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO_ARB1) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO16_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO16_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO16_12A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO16_12) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO16_8A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO16_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO16_4A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO16_4) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO12_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO12_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO12_12A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO12_12) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO12_8A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO12_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO12_4A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AO12_4) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_16E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_16E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_64MA) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_64ME) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_64MA) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_64M) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_64ME) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_32A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_32E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_32A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_32) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_32E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_64A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_64E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_64A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_64) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_64E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_96A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_96E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_96A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_96) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_96E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_128A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO16_128E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_128A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_128) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AIO12_128E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_NOFW_USB_AI16_2A) },
    // DEVICE ID'S AFTER FIRMWARE
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_32) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_32I) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_24) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_48) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_96) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_24_CTR6) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DI_16A_REV_A1) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DO_16A_REV_A1) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DI_16A_REV_A2) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_16H) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DI_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DO_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_IIRO_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_II_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_RO_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_IIRO_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_II_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_IIRO_4) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_IDIO_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_II_16_OEM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_IDO_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_IDIO_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_II_8_OEM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_IDIO_4) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_II_4_OEM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_CTR_15) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_IIRO4_2SM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_IIRO4_COM) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_16_RO_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_48_DO_24) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DIO_24_DO_12) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_DO_24) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_PICO_DIO_16_RO_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USBP_II8_IDO_4A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_PICO_II8_IDO_4A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_16E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_16E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_64MA) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_64ME) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_64MA) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_64M) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_64ME) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_32A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_32E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_32A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_32) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_32E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_64A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_64E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_64A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_64) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_64E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_96A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_96E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_96A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_96) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_96E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_128A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_128E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_128A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_128) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI12_128E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO_ARB1) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO16_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO16_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO16_12A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO16_12) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO16_8A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO16_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO16_4A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO16_4) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO12_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO12_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO12_12A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO12_12) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO12_8A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO12_8) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO12_4A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AO12_4) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_16E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_16A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_16) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_16E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_64MA) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_64ME) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_64MA) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_64M) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_64ME) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_32A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_32E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_32A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_32) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_32E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_64A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_64E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_64A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_64) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_64E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_96A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_96E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_96A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_96) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_96E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_128A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO16_128E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_128A) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_128) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AIO12_128E) },
    { USB_DEVICE(ACCESIO_USB_VID, ACCESIO_USB_AI16_2A) },
    { } // terminating entry
};
MODULE_DEVICE_TABLE(usb, accesio_usb_ids);

static uint8_t device_counters[ACCESIO_USB_CARD_COUNT+1];

// These functions are here to map names and device counters
// without utilizing a table or map that would use up kernel
// memory. These functions are only called in a few spots and
// don't need to take up memory just to resolve a name and id

static const char* get_name_from_id(unsigned int id) {
    switch (id) {
        // DEVICE ID'S
        case ACCESIO_USB_DA12_8A_REV_A:   return "usb_da12_8a_rev_a";
        case ACCESIO_USB_DA12_8A:         return "usb_da12_8a";
        case ACCESIO_USB_DA12_8E:         return "usb_da12_8e";
        // DEVICE ID'S AFTER FIRMWARE
        case ACCESIO_USB_DIO_32:          return "usb_dio_32";
        case ACCESIO_USB_DIO_32I:         return "usb_dio_32i";
        case ACCESIO_USB_DIO_24:          return "usb_dio_24";
        case ACCESIO_USB_DIO_48:          return "usb_dio_48";
        case ACCESIO_USB_DIO_96:          return "usb_dio_96";
        case ACCESIO_USB_DIO_24_CTR6:     return "usb_dio_24_ctr6";
        case ACCESIO_USB_DI_16A_REV_A1:   return "usb_di_16a_rev_a1";
        case ACCESIO_USB_DO_16A_REV_A1:   return "usb_do_16a_rev_a1";
        case ACCESIO_USB_DI_16A_REV_A2:   return "usb_di_16a_rev_a2";
        case ACCESIO_USB_DIO_16H:         return "usb_dio_16h";
        case ACCESIO_USB_DI_16A:          return "usb_di_16a";
        case ACCESIO_USB_DO_16A:          return "usb_do_16a";
        case ACCESIO_USB_DIO_16A:         return "usb_dio_16a";
        case ACCESIO_USB_IIRO_16:         return "usb_iiro_16";
        case ACCESIO_USB_II_16:           return "usb_ii_16";
        case ACCESIO_USB_RO_16:           return "usb_ro_16";
        case ACCESIO_USB_IIRO_8:          return "usb_iiro_8";
        case ACCESIO_USB_II_8:            return "usb_ii_8";
        case ACCESIO_USB_IIRO_4:          return "usb_iiro_4";
        case ACCESIO_USB_IDIO_16:         return "usb_idio_16";
        case ACCESIO_USB_II_16_OEM:       return "usb_ii_16_oem";
        case ACCESIO_USB_IDO_16:          return "usb_ido_16";
        case ACCESIO_USB_IDIO_8:          return "usb_idio_8";
        case ACCESIO_USB_II_8_OEM:        return "usb_ii_8_oem";
        case ACCESIO_USB_IDIO_4:          return "usb_idio_4";
        case ACCESIO_USB_II_4_OEM:        return "usb_ii_4_oem";
        case ACCESIO_USB_CTR_15:          return "usb_ctr_15";
        case ACCESIO_USB_IIRO4_2SM:       return "usb_iiro4_2sm";
        case ACCESIO_USB_IIRO4_COM:       return "usb_iiro4_com";
        case ACCESIO_USB_DIO_16_RO_8:     return "usb_dio_16_ro_8";
        case ACCESIO_USB_DIO_48_DO_24:    return "usb_dio_48_do_24";
        case ACCESIO_USB_DIO_24_DO_12:    return "usb_dio_24_do_12";
        case ACCESIO_USB_DO_24:           return "usb_do_24";
        case ACCESIO_PICO_DIO_16_RO_8:    return "pico_dio_16_ro_8";
        case ACCESIO_USBP_II8_IDO_4A:     return "usbp_ii8_ido_4a";
        case ACCESIO_PICO_II8_IDO_4A:     return "pico_ii8_ido_4a";
        case ACCESIO_USB_AI16_16A:        return "usb_ai16_16a";
        case ACCESIO_USB_AI16_16E:        return "usb_ai16_16e";
        case ACCESIO_USB_AI12_16A:        return "usb_ai12_16a";
        case ACCESIO_USB_AI12_16:         return "usb_ai12_16";
        case ACCESIO_USB_AI12_16E:        return "usb_ai12_16e";
        case ACCESIO_USB_AI16_64MA:       return "usb_ai16_64ma";
        case ACCESIO_USB_AI16_64ME:       return "usb_ai16_64me";
        case ACCESIO_USB_AI12_64MA:       return "usb_ai12_64ma";
        case ACCESIO_USB_AI12_64M:        return "usb_ai12_64m";
        case ACCESIO_USB_AI12_64ME:       return "usb_ai12_64me";
        case ACCESIO_USB_AI16_32A:        return "usb_ai16_32a";
        case ACCESIO_USB_AI16_32E:        return "usb_ai16_32e";
        case ACCESIO_USB_AI12_32A:        return "usb_ai12_32a";
        case ACCESIO_USB_AI12_32:         return "usb_ai12_32";
        case ACCESIO_USB_AI12_32E:        return "usb_ai12_32e";
        case ACCESIO_USB_AI16_64A:        return "usb_ai16_64a";
        case ACCESIO_USB_AI16_64E:        return "usb_ai16_64e";
        case ACCESIO_USB_AI12_64A:        return "usb_ai12_64a";
        case ACCESIO_USB_AI12_64:         return "usb_ai12_64";
        case ACCESIO_USB_AI12_64E:        return "usb_ai12_64e";
        case ACCESIO_USB_AI16_96A:        return "usb_ai16_96a";
        case ACCESIO_USB_AI16_96E:        return "usb_ai16_96e";
        case ACCESIO_USB_AI12_96A:        return "usb_ai12_96a";
        case ACCESIO_USB_AI12_96:         return "usb_ai12_96";
        case ACCESIO_USB_AI12_96E:        return "usb_ai12_96e";
        case ACCESIO_USB_AI16_128A:       return "usb_ai16_128a";
        case ACCESIO_USB_AI16_128E:       return "usb_ai16_128e";
        case ACCESIO_USB_AI12_128A:       return "usb_ai12_128a";
        case ACCESIO_USB_AI12_128:        return "usb_ai12_128";
        case ACCESIO_USB_AI12_128E:       return "usb_ai12_128e";
        case ACCESIO_USB_AO_ARB1:         return "usb_ao_arb1";
        case ACCESIO_USB_AO16_16A:        return "usb_ao16_16a";
        case ACCESIO_USB_AO16_16:         return "usb_ao16_16";
        case ACCESIO_USB_AO16_12A:        return "usb_ao16_12a";
        case ACCESIO_USB_AO16_12:         return "usb_ao16_12";
        case ACCESIO_USB_AO16_8A:         return "usb_ao16_8a";
        case ACCESIO_USB_AO16_8:          return "usb_ao16_8";
        case ACCESIO_USB_AO16_4A:         return "usb_ao16_4a";
        case ACCESIO_USB_AO16_4:          return "usb_ao16_4";
        case ACCESIO_USB_AO12_16A:        return "usb_ao12_16a";
        case ACCESIO_USB_AO12_16:         return "usb_ao12_16";
        case ACCESIO_USB_AO12_12A:        return "usb_ao12_12a";
        case ACCESIO_USB_AO12_12:         return "usb_ao12_12";
        case ACCESIO_USB_AO12_8A:         return "usb_ao12_8a";
        case ACCESIO_USB_AO12_8:          return "usb_ao12_8";
        case ACCESIO_USB_AO12_4A:         return "usb_ao12_4a";
        case ACCESIO_USB_AO12_4:          return "usb_ao12_4";
        case ACCESIO_USB_AIO16_16A:       return "usb_aio16_16a";
        case ACCESIO_USB_AIO16_16E:       return "usb_aio16_16e";
        case ACCESIO_USB_AIO12_16A:       return "usb_aio12_16a";
        case ACCESIO_USB_AIO12_16:        return "usb_aio12_16";
        case ACCESIO_USB_AIO12_16E:       return "usb_aio12_16e";
        case ACCESIO_USB_AIO16_64MA:      return "usb_aio16_64ma";
        case ACCESIO_USB_AIO16_64ME:      return "usb_aio16_64me";
        case ACCESIO_USB_AIO12_64MA:      return "usb_aio12_64ma";
        case ACCESIO_USB_AIO12_64M:       return "usb_aio12_64m";
        case ACCESIO_USB_AIO12_64ME:      return "usb_aio12_64me";
        case ACCESIO_USB_AIO16_32A:       return "usb_aio16_32a";
        case ACCESIO_USB_AIO16_32E:       return "usb_aio16_32e";
        case ACCESIO_USB_AIO12_32A:       return "usb_aio12_32a";
        case ACCESIO_USB_AIO12_32:        return "usb_aio12_32";
        case ACCESIO_USB_AIO12_32E:       return "usb_aio12_32e";
        case ACCESIO_USB_AIO16_64A:       return "usb_aio16_64a";
        case ACCESIO_USB_AIO16_64E:       return "usb_aio16_64e";
        case ACCESIO_USB_AIO12_64A:       return "usb_aio12_64a";
        case ACCESIO_USB_AIO12_64:        return "usb_aio12_64";
        case ACCESIO_USB_AIO12_64E:       return "usb_aio12_64e";
        case ACCESIO_USB_AIO16_96A:       return "usb_aio16_96a";
        case ACCESIO_USB_AIO16_96E:       return "usb_aio16_96e";
        case ACCESIO_USB_AIO12_96A:       return "usb_aio12_96a";
        case ACCESIO_USB_AIO12_96:        return "usb_aio12_96";
        case ACCESIO_USB_AIO12_96E:       return "usb_aio12_96e";
        case ACCESIO_USB_AIO16_128A:      return "usb_aio16_128a";
        case ACCESIO_USB_AIO16_128E:      return "usb_aio16_128e";
        case ACCESIO_USB_AIO12_128A:      return "usb_aio12_128a";
        case ACCESIO_USB_AIO12_128:       return "usb_aio12_128";
        case ACCESIO_USB_AIO12_128E:      return "usb_aio12_128e";
        case ACCESIO_USB_AI16_2A:         return "usb_ai16_2a";
        // DEVICE ID'S BEFORE FIRMWARE
        case ACCESIO_NOFW_USB_DIO_32:          return "usb_dio_32_nofw";
        case ACCESIO_NOFW_USB_DIO_32I:         return "usb_dio_32i_nofw";
        case ACCESIO_NOFW_USB_DIO_24:          return "usb_dio_24_nofw";
        case ACCESIO_NOFW_USB_DIO_48:          return "usb_dio_48_nofw";
        case ACCESIO_NOFW_USB_DIO_96:          return "usb_dio_96_nofw";
        case ACCESIO_NOFW_USB_DIO_24_CTR6:     return "usb_dio_24_ctr6_nofw";
        case ACCESIO_NOFW_USB_DI_16A_REV_A1:   return "usb_di_16a_rev_a1_nofw";
        case ACCESIO_NOFW_USB_DO_16A_REV_A1:   return "usb_do_16a_rev_a1_nofw";
        case ACCESIO_NOFW_USB_DI_16A_REV_A2:   return "usb_di_16a_rev_a2_nofw";
        case ACCESIO_NOFW_USB_DIO_16H:         return "usb_dio_16h_nofw";
        case ACCESIO_NOFW_USB_DI_16A:          return "usb_di_16a_nofw";
        case ACCESIO_NOFW_USB_DO_16A:          return "usb_do_16a_nofw";
        case ACCESIO_NOFW_USB_DIO_16A:         return "usb_dio_16a_nofw";
        case ACCESIO_NOFW_USB_IIRO_16:         return "usb_iiro_16_nofw";
        case ACCESIO_NOFW_USB_II_16:           return "usb_ii_16_nofw";
        case ACCESIO_NOFW_USB_RO_16:           return "usb_ro_16_nofw";
        case ACCESIO_NOFW_USB_IIRO_8:          return "usb_iiro_8_nofw";
        case ACCESIO_NOFW_USB_II_8:            return "usb_ii_8_nofw";
        case ACCESIO_NOFW_USB_IIRO_4:          return "usb_iiro_4_nofw";
        case ACCESIO_NOFW_USB_IDIO_16:         return "usb_idio_16_nofw";
        case ACCESIO_NOFW_USB_II_16_OEM:       return "usb_ii_16_oem_nofw";
        case ACCESIO_NOFW_USB_IDO_16:          return "usb_ido_16_nofw";
        case ACCESIO_NOFW_USB_IDIO_8:          return "usb_idio_8_nofw";
        case ACCESIO_NOFW_USB_II_8_OEM:        return "usb_ii_8_oem_nofw";
        case ACCESIO_NOFW_USB_IDIO_4:          return "usb_idio_4_nofw";
        case ACCESIO_NOFW_USB_II_4_OEM:        return "usb_ii_4_oem_nofw";
        case ACCESIO_NOFW_USB_CTR_15:          return "usb_ctr_15_nofw";
        case ACCESIO_NOFW_USB_IIRO4_2SM:       return "usb_iiro4_2sm_nofw";
        case ACCESIO_NOFW_USB_IIRO4_COM:       return "usb_iiro4_com_nofw";
        case ACCESIO_NOFW_USB_DIO_16_RO_8:     return "usb_dio_16_ro_8_nofw";
        case ACCESIO_NOFW_USB_DIO_48_DO_24:    return "usb_dio_48_do_24_nofw";
        case ACCESIO_NOFW_USB_DIO_24_DO_12:    return "usb_dio_24_do_12_nofw";
        case ACCESIO_NOFW_USB_DO_24:           return "usb_do_24_nofw";
        case ACCESIO_NOFW_PICO_DIO_16_RO_8:    return "pico_dio_16_ro_8_nofw";
        case ACCESIO_NOFW_USBP_II8_IDO_4A:     return "usbp_ii8_ido_4a_nofw";
        case ACCESIO_NOFW_PICO_II8_IDO_4A:     return "pico_ii8_ido_4a_nofw";
        case ACCESIO_NOFW_USB_AI16_16A:        return "usb_ai16_16a_nofw";
        case ACCESIO_NOFW_USB_AI16_16E:        return "usb_ai16_16e_nofw";
        case ACCESIO_NOFW_USB_AI12_16A:        return "usb_ai12_16a_nofw";
        case ACCESIO_NOFW_USB_AI12_16:         return "usb_ai12_16_nofw";
        case ACCESIO_NOFW_USB_AI12_16E:        return "usb_ai12_16e_nofw";
        case ACCESIO_NOFW_USB_AI16_64MA:       return "usb_ai16_64ma_nofw";
        case ACCESIO_NOFW_USB_AI16_64ME:       return "usb_ai16_64me_nofw";
        case ACCESIO_NOFW_USB_AI12_64MA:       return "usb_ai12_64ma_nofw";
        case ACCESIO_NOFW_USB_AI12_64M:        return "usb_ai12_64m_nofw";
        case ACCESIO_NOFW_USB_AI12_64ME:       return "usb_ai12_64me_nofw";
        case ACCESIO_NOFW_USB_AI16_32A:        return "usb_ai16_32a_nofw";
        case ACCESIO_NOFW_USB_AI16_32E:        return "usb_ai16_32e_nofw";
        case ACCESIO_NOFW_USB_AI12_32A:        return "usb_ai12_32a_nofw";
        case ACCESIO_NOFW_USB_AI12_32:         return "usb_ai12_32_nofw";
        case ACCESIO_NOFW_USB_AI12_32E:        return "usb_ai12_32e_nofw";
        case ACCESIO_NOFW_USB_AI16_64A:        return "usb_ai16_64a_nofw";
        case ACCESIO_NOFW_USB_AI16_64E:        return "usb_ai16_64e_nofw";
        case ACCESIO_NOFW_USB_AI12_64A:        return "usb_ai12_64a_nofw";
        case ACCESIO_NOFW_USB_AI12_64:         return "usb_ai12_64_nofw";
        case ACCESIO_NOFW_USB_AI12_64E:        return "usb_ai12_64e_nofw";
        case ACCESIO_NOFW_USB_AI16_96A:        return "usb_ai16_96a_nofw";
        case ACCESIO_NOFW_USB_AI16_96E:        return "usb_ai16_96e_nofw";
        case ACCESIO_NOFW_USB_AI12_96A:        return "usb_ai12_96a_nofw";
        case ACCESIO_NOFW_USB_AI12_96:         return "usb_ai12_96_nofw";
        case ACCESIO_NOFW_USB_AI12_96E:        return "usb_ai12_96e_nofw";
        case ACCESIO_NOFW_USB_AI16_128A:       return "usb_ai16_128a_nofw";
        case ACCESIO_NOFW_USB_AI16_128E:       return "usb_ai16_128e_nofw";
        case ACCESIO_NOFW_USB_AI12_128A:       return "usb_ai12_128a_nofw";
        case ACCESIO_NOFW_USB_AI12_128:        return "usb_ai12_128_nofw";
        case ACCESIO_NOFW_USB_AI12_128E:       return "usb_ai12_128e_nofw";
        case ACCESIO_NOFW_USB_AO_ARB1:         return "usb_ao_arb1_nofw";
        case ACCESIO_NOFW_USB_AO16_16A:        return "usb_ao16_16a_nofw";
        case ACCESIO_NOFW_USB_AO16_16:         return "usb_ao16_16_nofw";
        case ACCESIO_NOFW_USB_AO16_12A:        return "usb_ao16_12a_nofw";
        case ACCESIO_NOFW_USB_AO16_12:         return "usb_ao16_12_nofw";
        case ACCESIO_NOFW_USB_AO16_8A:         return "usb_ao16_8a_nofw";
        case ACCESIO_NOFW_USB_AO16_8:          return "usb_ao16_8_nofw";
        case ACCESIO_NOFW_USB_AO16_4A:         return "usb_ao16_4a_nofw";
        case ACCESIO_NOFW_USB_AO16_4:          return "usb_ao16_4_nofw";
        case ACCESIO_NOFW_USB_AO12_16A:        return "usb_ao12_16a_nofw";
        case ACCESIO_NOFW_USB_AO12_16:         return "usb_ao12_16_nofw";
        case ACCESIO_NOFW_USB_AO12_12A:        return "usb_ao12_12a_nofw";
        case ACCESIO_NOFW_USB_AO12_12:         return "usb_ao12_12_nofw";
        case ACCESIO_NOFW_USB_AO12_8A:         return "usb_ao12_8a_nofw";
        case ACCESIO_NOFW_USB_AO12_8:          return "usb_ao12_8_nofw";
        case ACCESIO_NOFW_USB_AO12_4A:         return "usb_ao12_4a_nofw";
        case ACCESIO_NOFW_USB_AO12_4:          return "usb_ao12_4_nofw";
        case ACCESIO_NOFW_USB_AIO16_16A:       return "usb_aio16_16a_nofw";
        case ACCESIO_NOFW_USB_AIO16_16E:       return "usb_aio16_16e_nofw";
        case ACCESIO_NOFW_USB_AIO12_16A:       return "usb_aio12_16a_nofw";
        case ACCESIO_NOFW_USB_AIO12_16:        return "usb_aio12_16_nofw";
        case ACCESIO_NOFW_USB_AIO12_16E:       return "usb_aio12_16e_nofw";
        case ACCESIO_NOFW_USB_AIO16_64MA:      return "usb_aio16_64ma_nofw";
        case ACCESIO_NOFW_USB_AIO16_64ME:      return "usb_aio16_64me_nofw";
        case ACCESIO_NOFW_USB_AIO12_64MA:      return "usb_aio12_64ma_nofw";
        case ACCESIO_NOFW_USB_AIO12_64M:       return "usb_aio12_64m_nofw";
        case ACCESIO_NOFW_USB_AIO12_64ME:      return "usb_aio12_64me_nofw";
        case ACCESIO_NOFW_USB_AIO16_32A:       return "usb_aio16_32a_nofw";
        case ACCESIO_NOFW_USB_AIO16_32E:       return "usb_aio16_32e_nofw";
        case ACCESIO_NOFW_USB_AIO12_32A:       return "usb_aio12_32a_nofw";
        case ACCESIO_NOFW_USB_AIO12_32:        return "usb_aio12_32_nofw";
        case ACCESIO_NOFW_USB_AIO12_32E:       return "usb_aio12_32e_nofw";
        case ACCESIO_NOFW_USB_AIO16_64A:       return "usb_aio16_64a_nofw";
        case ACCESIO_NOFW_USB_AIO16_64E:       return "usb_aio16_64e_nofw";
        case ACCESIO_NOFW_USB_AIO12_64A:       return "usb_aio12_64a_nofw";
        case ACCESIO_NOFW_USB_AIO12_64:        return "usb_aio12_64_nofw";
        case ACCESIO_NOFW_USB_AIO12_64E:       return "usb_aio12_64e_nofw";
        case ACCESIO_NOFW_USB_AIO16_96A:       return "usb_aio16_96a_nofw";
        case ACCESIO_NOFW_USB_AIO16_96E:       return "usb_aio16_96e_nofw";
        case ACCESIO_NOFW_USB_AIO12_96A:       return "usb_aio12_96a_nofw";
        case ACCESIO_NOFW_USB_AIO12_96:        return "usb_aio12_96_nofw";
        case ACCESIO_NOFW_USB_AIO12_96E:       return "usb_aio12_96e_nofw";
        case ACCESIO_NOFW_USB_AIO16_128A:      return "usb_aio16_128a_nofw";
        case ACCESIO_NOFW_USB_AIO16_128E:      return "usb_aio16_128e_nofw";
        case ACCESIO_NOFW_USB_AIO12_128A:      return "usb_aio12_128a_nofw";
        case ACCESIO_NOFW_USB_AIO12_128:       return "usb_aio12_128_nofw";
        case ACCESIO_NOFW_USB_AIO12_128E:      return "usb_aio12_128e_nofw";
        case ACCESIO_NOFW_USB_AI16_2A:         return "usb_ai16_2a_nofw";
        default: break;
    }
    return "unknown_usb";
}

static const char* get_fw_name_from_id(unsigned int id) {
    switch (id) {
        // UNKNOWN FW
        case ACCESIO_USB_DI_16A_REV_A1: return "ACCESIO-USB-DI-16A-REV-A1.hex";
        case ACCESIO_USB_DO_16A_REV_A1: return "ACCESIO-USB-DO-16A-REV-A1.hex";
        case ACCESIO_USB_DA12_8A_REV_A: return "ACCESIO-USB-DA12-8A-REV-A.hex";
        case ACCESIO_USB_DI_16A_REV_A2: return "ACCESIO-USB-DI-16A-REV-A2.hex";

        // KNOWN-DO-NOT-HAVE
        case ACCESIO_USB_II_4_OEM:
        case ACCESIO_USB_II_8_OEM:
        case ACCESIO_USB_II_16_OEM:     return "ACCESIO-USB-II-16-OEM.hex";

        case ACCESIO_PICO_II8_IDO_4A:   return "ACCESIO-PICO-II8-IDO-4A.hex";
        case ACCESIO_USB_DIO_48_DO_24:  return "ACCESIO-USB-DIO-48-DO-24.hex";
        case ACCESIO_USB_DIO_24_DO_12:  return "ACCESIO-USB-DIO-24-DO-12.hex";
        case ACCESIO_USB_DO_24:         return "ACCESIO-USB-DO-24.hex";
        case ACCESIO_USB_AI16_2A:       return "ACCESIO-USB-AI16-2A.hex";


        // DEVICE ID'S MATCHED TO FW
        case ACCESIO_USB_DA12_8A:       return "ACCESIO-USB-DA12-8A.hex"; /* fw/ */
        case ACCESIO_USB_DA12_8E:       return "ACCESIO-USB-DA12-8E.hex"; /* fw/ */
        case ACCESIO_USB_DIO_32:        return "ACCESIO-USB-DIO-32.hex"; /* fw/ */
        case ACCESIO_USB_DIO_32I:       return "ACCESIO-USB-DIO-32I.hex"; /* fw/ */
        case ACCESIO_USB_DIO_48:        return "ACCESIO-USB-DIO-48.hex"; /* fw/ */
        case ACCESIO_USB_DIO_96:        return "ACCESIO-USB-DIO-96.hex"; /* fw/ */

        case ACCESIO_USB_DIO_24:        
        case ACCESIO_USB_DIO_24_CTR6:   return "ACCESIO-USB-DIO-24-CTR6.hex"; /* fw/ */

        case ACCESIO_USB_DIO_16H:       
        case ACCESIO_USB_DI_16A:        
        case ACCESIO_USB_DO_16A:        
        case ACCESIO_USB_DIO_16A:       return "ACCESIO-USB-DIO-16A.hex"; /* fw/ */

        case ACCESIO_USB_II_16:
        case ACCESIO_USB_RO_16:
        case ACCESIO_USB_IIRO_8:
        case ACCESIO_USB_II_8:
        case ACCESIO_USB_IIRO_4:
        case ACCESIO_USB_IDO_16:
        case ACCESIO_USB_IDIO_8:
        case ACCESIO_USB_IDIO_4:
        case ACCESIO_USB_IIRO_16:       return "ACCESIO-USB-IIRO-16.hex"; /* fw/ */

        case ACCESIO_USB_IDIO_16:       return "ACCESIO-USB-IDIO-16.hex"; /* fw/ */
        case ACCESIO_USB_CTR_15:        return "ACCESIO-USB-CTR-15.hex"; /* fw/ */
        case ACCESIO_USB_IIRO4_2SM:     return "ACCESIO-USB-IIRO4-2SM.hex"; /* fw/ */
        case ACCESIO_USB_IIRO4_COM:     return "ACCESIO-USB-IIRO4-COM.hex"; /* fw/ */
        case ACCESIO_USB_DIO_16_RO_8:   return "ACCESIO-USB-DIO-16-RO-8.hex"; /* fw/ */
        case ACCESIO_PICO_DIO_16_RO_8:  return "ACCESIO-PICO-DIO-16-RO-8.hex"; /* fw/ */
        case ACCESIO_USBP_II8_IDO_4A:   return "ACCESIO-USBP-II8-IDO-4A.hex"; /* fw/ */
        case ACCESIO_USB_AO_ARB1:       return "ACCESIO-USB-AO-ARB1.hex"; /* fw/ */
        
        case ACCESIO_USB_AI16_16E:
        case ACCESIO_USB_AI12_16A:
        case ACCESIO_USB_AI12_16:
        case ACCESIO_USB_AI12_16E:
        case ACCESIO_USB_AI16_64MA:
        case ACCESIO_USB_AI16_64ME:
        case ACCESIO_USB_AI12_64MA:
        case ACCESIO_USB_AI12_64M:
        case ACCESIO_USB_AI12_64ME:
        case ACCESIO_USB_AI16_32A:
        case ACCESIO_USB_AI16_32E:
        case ACCESIO_USB_AI12_32A:
        case ACCESIO_USB_AI12_32:
        case ACCESIO_USB_AI12_32E:
        case ACCESIO_USB_AI16_64A:
        case ACCESIO_USB_AI16_64E:
        case ACCESIO_USB_AI12_64A:
        case ACCESIO_USB_AI12_64:
        case ACCESIO_USB_AI12_64E:
        case ACCESIO_USB_AI16_96A:
        case ACCESIO_USB_AI16_96E:
        case ACCESIO_USB_AI12_96A:
        case ACCESIO_USB_AI12_96:
        case ACCESIO_USB_AI12_96E:
        case ACCESIO_USB_AI16_128A:
        case ACCESIO_USB_AI16_128E:
        case ACCESIO_USB_AI12_128A:
        case ACCESIO_USB_AI12_128:
        case ACCESIO_USB_AI12_128E:
        case ACCESIO_USB_AI16_16A:      return "ACCESIO-USB-AI16-16A.hex"; /* fw/ */

        case ACCESIO_USB_AO16_12A:
        case ACCESIO_USB_AO16_8A:
        case ACCESIO_USB_AO16_4A:
        case ACCESIO_USB_AO12_16A:
        case ACCESIO_USB_AO12_12A:
        case ACCESIO_USB_AO12_8A:
        case ACCESIO_USB_AO12_4A:
        case ACCESIO_USB_AO16_16A:      return "ACCESIO-USB-AO16-16A.hex"; /* fw/ */

        case ACCESIO_USB_AO16_12:
        case ACCESIO_USB_AO16_8:
        case ACCESIO_USB_AO16_4:
        case ACCESIO_USB_AO12_16:
        case ACCESIO_USB_AO12_12:
        case ACCESIO_USB_AO12_8:
        case ACCESIO_USB_AO12_4:
        case ACCESIO_USB_AO16_16:       return "ACCESIO-USB-AO16-16.hex"; /* fw/ */

        case ACCESIO_USB_AIO16_16E:
        case ACCESIO_USB_AIO12_16A:
        case ACCESIO_USB_AIO12_16:
        case ACCESIO_USB_AIO12_16E:
        case ACCESIO_USB_AIO16_64MA:
        case ACCESIO_USB_AIO16_64ME:
        case ACCESIO_USB_AIO12_64MA:
        case ACCESIO_USB_AIO12_64M:
        case ACCESIO_USB_AIO12_64ME:
        case ACCESIO_USB_AIO16_32A:
        case ACCESIO_USB_AIO16_32E:
        case ACCESIO_USB_AIO12_32A:
        case ACCESIO_USB_AIO12_32:
        case ACCESIO_USB_AIO12_32E:
        case ACCESIO_USB_AIO16_64A:
        case ACCESIO_USB_AIO16_64E:
        case ACCESIO_USB_AIO12_64A:
        case ACCESIO_USB_AIO12_64:
        case ACCESIO_USB_AIO12_64E:
        case ACCESIO_USB_AIO16_96A:
        case ACCESIO_USB_AIO16_96E:
        case ACCESIO_USB_AIO12_96A:
        case ACCESIO_USB_AIO12_96:
        case ACCESIO_USB_AIO12_96E:
        case ACCESIO_USB_AIO16_128A:
        case ACCESIO_USB_AIO16_128E:
        case ACCESIO_USB_AIO12_128A:
        case ACCESIO_USB_AIO12_128:
        case ACCESIO_USB_AIO12_128E:
        case ACCESIO_USB_AIO16_16A:     return "ACCESIO-USB-AIO16-16A.hex"; /* fw/ */

        default: break;
    }
    return NULL;
}

static inline int get_counter_from_id(unsigned int id) {
    switch (id) {
        // DEVICE ID'S
        case ACCESIO_USB_DA12_8A_REV_A:   return 1;
        case ACCESIO_USB_DA12_8A:         return 2;
        case ACCESIO_USB_DA12_8E:         return 3;
        // DEVICE ID'S AFTER FIRMWARE
        case ACCESIO_USB_DIO_32:          return 4;
        case ACCESIO_USB_DIO_32I:         return 5;
        case ACCESIO_USB_DIO_24:          return 6;
        case ACCESIO_USB_DIO_48:          return 7;
        case ACCESIO_USB_DIO_96:          return 8;
        case ACCESIO_USB_DIO_24_CTR6:     return 9;
        case ACCESIO_USB_DI_16A_REV_A1:   return 10;
        case ACCESIO_USB_DO_16A_REV_A1:   return 11;
        case ACCESIO_USB_DI_16A_REV_A2:   return 12;
        case ACCESIO_USB_DIO_16H:         return 13;
        case ACCESIO_USB_DI_16A:          return 14;
        case ACCESIO_USB_DO_16A:          return 15;
        case ACCESIO_USB_DIO_16A:         return 16;
        case ACCESIO_USB_IIRO_16:         return 17;
        case ACCESIO_USB_II_16:           return 18;
        case ACCESIO_USB_RO_16:           return 19;
        case ACCESIO_USB_IIRO_8:          return 20;
        case ACCESIO_USB_II_8:            return 21;
        case ACCESIO_USB_IIRO_4:          return 22;
        case ACCESIO_USB_IDIO_16:         return 23;
        case ACCESIO_USB_II_16_OEM:       return 24;
        case ACCESIO_USB_IDO_16:          return 25;
        case ACCESIO_USB_IDIO_8:          return 26;
        case ACCESIO_USB_II_8_OEM:        return 27;
        case ACCESIO_USB_IDIO_4:          return 28;
        case ACCESIO_USB_CTR_15:          return 29;
        case ACCESIO_USB_IIRO4_2SM:       return 30;
        case ACCESIO_USB_IIRO4_COM:       return 31;
        case ACCESIO_USB_DIO_16_RO_8:     return 32;
        case ACCESIO_USB_DIO_48_DO_24:    return 33;
        case ACCESIO_USB_DIO_24_DO_12:    return 34;
        case ACCESIO_USB_DO_24:           return 35;
        case ACCESIO_PICO_DIO_16_RO_8:    return 36;
        case ACCESIO_USBP_II8_IDO_4A:     return 37;
        case ACCESIO_USB_AI16_16A:        return 38;
        case ACCESIO_USB_AI16_16E:        return 39;
        case ACCESIO_USB_AI12_16A:        return 40;
        case ACCESIO_USB_AI12_16:         return 41;
        case ACCESIO_USB_AI12_16E:        return 42;
        case ACCESIO_USB_AI16_64MA:       return 43;
        case ACCESIO_USB_AI16_64ME:       return 44;
        case ACCESIO_USB_AI12_64MA:       return 45;
        case ACCESIO_USB_AI12_64M:        return 46;
        case ACCESIO_USB_AI12_64ME:       return 47;
        case ACCESIO_USB_AI16_32A:        return 48;
        case ACCESIO_USB_AI16_32E:        return 49;
        case ACCESIO_USB_AI12_32A:        return 50;
        case ACCESIO_USB_AI12_32:         return 51;
        case ACCESIO_USB_AI12_32E:        return 52;
        case ACCESIO_USB_AI16_64A:        return 53;
        case ACCESIO_USB_AI16_64E:        return 54;
        case ACCESIO_USB_AI12_64A:        return 55;
        case ACCESIO_USB_AI12_64:         return 56;
        case ACCESIO_USB_AI12_64E:        return 57;
        case ACCESIO_USB_AI16_96A:        return 58;
        case ACCESIO_USB_AI16_96E:        return 59;
        case ACCESIO_USB_AI12_96A:        return 60;
        case ACCESIO_USB_AI12_96:         return 61;
        case ACCESIO_USB_AI12_96E:        return 62;
        case ACCESIO_USB_AI16_128A:       return 63;
        case ACCESIO_USB_AI16_128E:       return 64;
        case ACCESIO_USB_AI12_128A:       return 65;
        case ACCESIO_USB_AI12_128:        return 66;
        case ACCESIO_USB_AI12_128E:       return 67;
        case ACCESIO_USB_AO_ARB1:         return 68;
        case ACCESIO_USB_AO16_16A:        return 69;
        case ACCESIO_USB_AO16_16:         return 70;
        case ACCESIO_USB_AO16_12A:        return 71;
        case ACCESIO_USB_AO16_12:         return 72;
        case ACCESIO_USB_AO16_8A:         return 73;
        case ACCESIO_USB_AO16_8:          return 74;
        case ACCESIO_USB_AO16_4A:         return 75;
        case ACCESIO_USB_AO16_4:          return 76;
        case ACCESIO_USB_AO12_16A:        return 77;
        case ACCESIO_USB_AO12_16:         return 78;
        case ACCESIO_USB_AO12_12A:        return 79;
        case ACCESIO_USB_AO12_12:         return 80;
        case ACCESIO_USB_AO12_8A:         return 81;
        case ACCESIO_USB_AO12_8:          return 82;
        case ACCESIO_USB_AO12_4A:         return 83;
        case ACCESIO_USB_AO12_4:          return 84;
        case ACCESIO_USB_AIO16_16A:       return 85;
        case ACCESIO_USB_AIO16_16E:       return 86;
        case ACCESIO_USB_AIO12_16A:       return 87;
        case ACCESIO_USB_AIO12_16:        return 89;
        case ACCESIO_USB_AIO12_16E:       return 90;
        case ACCESIO_USB_AIO16_64MA:      return 91;
        case ACCESIO_USB_AIO16_64ME:      return 92;
        case ACCESIO_USB_AIO12_64MA:      return 93;
        case ACCESIO_USB_AIO12_64M:       return 94;
        case ACCESIO_USB_AIO12_64ME:      return 95;
        case ACCESIO_USB_AIO16_32A:       return 96;
        case ACCESIO_USB_AIO16_32E:       return 97;
        case ACCESIO_USB_AIO12_32A:       return 98;
        case ACCESIO_USB_AIO12_32:        return 99;
        case ACCESIO_USB_AIO12_32E:       return 100;
        case ACCESIO_USB_AIO16_64A:       return 101;
        case ACCESIO_USB_AIO16_64E:       return 102;
        case ACCESIO_USB_AIO12_64A:       return 103;
        case ACCESIO_USB_AIO12_64:        return 104;
        case ACCESIO_USB_AIO12_64E:       return 105;
        case ACCESIO_USB_AIO16_96A:       return 106;
        case ACCESIO_USB_AIO16_96E:       return 107;
        case ACCESIO_USB_AIO12_96A:       return 108;
        case ACCESIO_USB_AIO12_96:        return 109;
        case ACCESIO_USB_AIO12_96E:       return 110;
        case ACCESIO_USB_AIO16_128A:      return 111;
        case ACCESIO_USB_AIO16_128E:      return 112;
        case ACCESIO_USB_AIO12_128A:      return 113;
        case ACCESIO_USB_AIO12_128:       return 114;
        case ACCESIO_USB_AIO12_128E:      return 115;
        case ACCESIO_USB_II_4_OEM:        return 116;
        case ACCESIO_USB_AI16_2A:         return 117;
        default: break;
    }
    return 0;
}

static inline int get_device_counter(unsigned int id) {
    return device_counters[get_counter_from_id(id)];
}

static inline int decrement_device_id(unsigned int id) {
    return --device_counters[get_counter_from_id(id)];
}

static inline int increment_device_id(unsigned int id) {
    return device_counters[get_counter_from_id(id)]++;
}

static const bool is_nonfw_device(unsigned int id) {
    switch (id) {
        case ACCESIO_NOFW_USB_DIO_32:
        case ACCESIO_NOFW_USB_DIO_32I:
        case ACCESIO_NOFW_USB_DIO_24:
        case ACCESIO_NOFW_USB_DIO_48:
        case ACCESIO_NOFW_USB_DIO_96:
        case ACCESIO_NOFW_USB_DIO_24_CTR6:
        case ACCESIO_NOFW_USB_DI_16A_REV_A1:
        case ACCESIO_NOFW_USB_DO_16A_REV_A1:
        case ACCESIO_NOFW_USB_DI_16A_REV_A2:
        case ACCESIO_NOFW_USB_DIO_16H:
        case ACCESIO_NOFW_USB_DI_16A:
        case ACCESIO_NOFW_USB_DO_16A:
        case ACCESIO_NOFW_USB_DIO_16A:
        case ACCESIO_NOFW_USB_IIRO_16:
        case ACCESIO_NOFW_USB_II_16:
        case ACCESIO_NOFW_USB_RO_16:
        case ACCESIO_NOFW_USB_IIRO_8:
        case ACCESIO_NOFW_USB_II_8:
        case ACCESIO_NOFW_USB_IIRO_4:
        case ACCESIO_NOFW_USB_IDIO_16:
        case ACCESIO_NOFW_USB_II_16_OEM:
        case ACCESIO_NOFW_USB_IDO_16:
        case ACCESIO_NOFW_USB_IDIO_8:
        case ACCESIO_NOFW_USB_II_8_OEM:
        case ACCESIO_NOFW_USB_IDIO_4:
        case ACCESIO_NOFW_USB_II_4_OEM:
        case ACCESIO_NOFW_USB_CTR_15:
        case ACCESIO_NOFW_USB_IIRO4_2SM:
        case ACCESIO_NOFW_USB_IIRO4_COM:
        case ACCESIO_NOFW_USB_DIO_16_RO_8:
        case ACCESIO_NOFW_USB_DIO_48_DO_24:
        case ACCESIO_NOFW_USB_DIO_24_DO_12:
        case ACCESIO_NOFW_USB_DO_24:
        case ACCESIO_NOFW_PICO_DIO_16_RO_8:
        case ACCESIO_NOFW_USBP_II8_IDO_4A:
        case ACCESIO_NOFW_USB_AI16_16A:
        case ACCESIO_NOFW_USB_AI16_16E:
        case ACCESIO_NOFW_USB_AI12_16A:
        case ACCESIO_NOFW_USB_AI12_16:
        case ACCESIO_NOFW_USB_AI12_16E:
        case ACCESIO_NOFW_USB_AI16_64MA:
        case ACCESIO_NOFW_USB_AI16_64ME:
        case ACCESIO_NOFW_USB_AI12_64MA:
        case ACCESIO_NOFW_USB_AI12_64M:
        case ACCESIO_NOFW_USB_AI12_64ME:
        case ACCESIO_NOFW_USB_AI16_32A:
        case ACCESIO_NOFW_USB_AI16_32E:
        case ACCESIO_NOFW_USB_AI12_32A:
        case ACCESIO_NOFW_USB_AI12_32:
        case ACCESIO_NOFW_USB_AI12_32E:
        case ACCESIO_NOFW_USB_AI16_64A:
        case ACCESIO_NOFW_USB_AI16_64E:
        case ACCESIO_NOFW_USB_AI12_64A:
        case ACCESIO_NOFW_USB_AI12_64:
        case ACCESIO_NOFW_USB_AI12_64E:
        case ACCESIO_NOFW_USB_AI16_96A:
        case ACCESIO_NOFW_USB_AI16_96E:
        case ACCESIO_NOFW_USB_AI12_96A:
        case ACCESIO_NOFW_USB_AI12_96:
        case ACCESIO_NOFW_USB_AI12_96E:
        case ACCESIO_NOFW_USB_AI16_128A:
        case ACCESIO_NOFW_USB_AI16_128E:
        case ACCESIO_NOFW_USB_AI12_128A:
        case ACCESIO_NOFW_USB_AI12_128:
        case ACCESIO_NOFW_USB_AI12_128E:
        case ACCESIO_NOFW_USB_AO_ARB1:
        case ACCESIO_NOFW_USB_AO16_16A:
        case ACCESIO_NOFW_USB_AO16_16:
        case ACCESIO_NOFW_USB_AO16_12A:
        case ACCESIO_NOFW_USB_AO16_12:
        case ACCESIO_NOFW_USB_AO16_8A:
        case ACCESIO_NOFW_USB_AO16_8:
        case ACCESIO_NOFW_USB_AO16_4A:
        case ACCESIO_NOFW_USB_AO16_4:
        case ACCESIO_NOFW_USB_AO12_16A:
        case ACCESIO_NOFW_USB_AO12_16:
        case ACCESIO_NOFW_USB_AO12_12A:
        case ACCESIO_NOFW_USB_AO12_12:
        case ACCESIO_NOFW_USB_AO12_8A:
        case ACCESIO_NOFW_USB_AO12_8:
        case ACCESIO_NOFW_USB_AO12_4A:
        case ACCESIO_NOFW_USB_AO12_4:
        case ACCESIO_NOFW_USB_AIO16_16A:
        case ACCESIO_NOFW_USB_AIO16_16E:
        case ACCESIO_NOFW_USB_AIO12_16A:
        case ACCESIO_NOFW_USB_AIO12_16:
        case ACCESIO_NOFW_USB_AIO12_16E:
        case ACCESIO_NOFW_USB_AIO16_64MA:
        case ACCESIO_NOFW_USB_AIO16_64ME:
        case ACCESIO_NOFW_USB_AIO12_64MA:
        case ACCESIO_NOFW_USB_AIO12_64M:
        case ACCESIO_NOFW_USB_AIO12_64ME:
        case ACCESIO_NOFW_USB_AIO16_32A:
        case ACCESIO_NOFW_USB_AIO16_32E:
        case ACCESIO_NOFW_USB_AIO12_32A:
        case ACCESIO_NOFW_USB_AIO12_32:
        case ACCESIO_NOFW_USB_AIO12_32E:
        case ACCESIO_NOFW_USB_AIO16_64A:
        case ACCESIO_NOFW_USB_AIO16_64E:
        case ACCESIO_NOFW_USB_AIO12_64A:
        case ACCESIO_NOFW_USB_AIO12_64:
        case ACCESIO_NOFW_USB_AIO12_64E:
        case ACCESIO_NOFW_USB_AIO16_96A:
        case ACCESIO_NOFW_USB_AIO16_96E:
        case ACCESIO_NOFW_USB_AIO12_96A:
        case ACCESIO_NOFW_USB_AIO12_96:
        case ACCESIO_NOFW_USB_AIO12_96E:
        case ACCESIO_NOFW_USB_AIO16_128A:
        case ACCESIO_NOFW_USB_AIO16_128E:
        case ACCESIO_NOFW_USB_AIO12_128A:
        case ACCESIO_NOFW_USB_AIO12_128:
        case ACCESIO_NOFW_USB_AIO12_128E:
        case ACCESIO_NOFW_USB_AI16_2A:
            return true;
        default: break;
    }
    return false;
}

static const int get_fw_id_from_nonfw_id(unsigned int id) {
    switch (id) {
        case ACCESIO_NOFW_USB_DIO_32:          return ACCESIO_USB_DIO_32;
        case ACCESIO_NOFW_USB_DIO_32I:         return ACCESIO_USB_DIO_32I;
        case ACCESIO_NOFW_USB_DIO_24:          return ACCESIO_USB_DIO_24;
        case ACCESIO_NOFW_USB_DIO_48:          return ACCESIO_USB_DIO_48;
        case ACCESIO_NOFW_USB_DIO_96:          return ACCESIO_USB_DIO_96;
        case ACCESIO_NOFW_USB_DIO_24_CTR6:     return ACCESIO_USB_DIO_24_CTR6;
        case ACCESIO_NOFW_USB_DI_16A_REV_A1:   return ACCESIO_USB_DI_16A_REV_A1;
        case ACCESIO_NOFW_USB_DO_16A_REV_A1:   return ACCESIO_USB_DO_16A_REV_A1;
        case ACCESIO_NOFW_USB_DI_16A_REV_A2:   return ACCESIO_USB_DI_16A_REV_A2;
        case ACCESIO_NOFW_USB_DIO_16H:         return ACCESIO_USB_DIO_16H;
        case ACCESIO_NOFW_USB_DI_16A:          return ACCESIO_USB_DI_16A;
        case ACCESIO_NOFW_USB_DO_16A:          return ACCESIO_USB_DO_16A;
        case ACCESIO_NOFW_USB_DIO_16A:         return ACCESIO_USB_DIO_16A;
        case ACCESIO_NOFW_USB_IIRO_16:         return ACCESIO_USB_IIRO_16;
        case ACCESIO_NOFW_USB_II_16:           return ACCESIO_USB_II_16;
        case ACCESIO_NOFW_USB_RO_16:           return ACCESIO_USB_RO_16;
        case ACCESIO_NOFW_USB_IIRO_8:          return ACCESIO_USB_IIRO_8;
        case ACCESIO_NOFW_USB_II_8:            return ACCESIO_USB_II_8;
        case ACCESIO_NOFW_USB_IIRO_4:          return ACCESIO_USB_IIRO_4;
        case ACCESIO_NOFW_USB_IDIO_16:         return ACCESIO_USB_IDIO_16;
        case ACCESIO_NOFW_USB_II_16_OEM:       return ACCESIO_USB_II_16_OEM;
        case ACCESIO_NOFW_USB_IDO_16:          return ACCESIO_USB_IDO_16;
        case ACCESIO_NOFW_USB_IDIO_8:          return ACCESIO_USB_IDIO_8;
        case ACCESIO_NOFW_USB_II_8_OEM:        return ACCESIO_USB_II_8_OEM;
        case ACCESIO_NOFW_USB_IDIO_4:          return ACCESIO_USB_IDIO_4;
        case ACCESIO_NOFW_USB_II_4_OEM:        return ACCESIO_USB_II_4_OEM;
        case ACCESIO_NOFW_USB_CTR_15:          return ACCESIO_USB_CTR_15;
        case ACCESIO_NOFW_USB_IIRO4_2SM:       return ACCESIO_USB_IIRO4_2SM;
        case ACCESIO_NOFW_USB_IIRO4_COM:       return ACCESIO_USB_IIRO4_COM;
        case ACCESIO_NOFW_USB_DIO_16_RO_8:     return ACCESIO_USB_DIO_16_RO_8;
        case ACCESIO_NOFW_USB_DIO_48_DO_24:    return ACCESIO_USB_DIO_48_DO_24;
        case ACCESIO_NOFW_USB_DIO_24_DO_12:    return ACCESIO_USB_DIO_24_DO_12;
        case ACCESIO_NOFW_USB_DO_24:           return ACCESIO_USB_DO_24;
        case ACCESIO_NOFW_PICO_DIO_16_RO_8:    return ACCESIO_PICO_DIO_16_RO_8;
        case ACCESIO_NOFW_USBP_II8_IDO_4A:     return ACCESIO_USBP_II8_IDO_4A;
        case ACCESIO_NOFW_USB_AI16_16A:        return ACCESIO_USB_AI16_16A;
        case ACCESIO_NOFW_USB_AI16_16E:        return ACCESIO_USB_AI16_16E;
        case ACCESIO_NOFW_USB_AI12_16A:        return ACCESIO_USB_AI12_16A;
        case ACCESIO_NOFW_USB_AI12_16:         return ACCESIO_USB_AI12_16;
        case ACCESIO_NOFW_USB_AI12_16E:        return ACCESIO_USB_AI12_16E;
        case ACCESIO_NOFW_USB_AI16_64MA:       return ACCESIO_USB_AI16_64MA;
        case ACCESIO_NOFW_USB_AI16_64ME:       return ACCESIO_USB_AI16_64ME;
        case ACCESIO_NOFW_USB_AI12_64MA:       return ACCESIO_USB_AI12_64MA;
        case ACCESIO_NOFW_USB_AI12_64M:        return ACCESIO_USB_AI12_64M;
        case ACCESIO_NOFW_USB_AI12_64ME:       return ACCESIO_USB_AI12_64ME;
        case ACCESIO_NOFW_USB_AI16_32A:        return ACCESIO_USB_AI16_32A;
        case ACCESIO_NOFW_USB_AI16_32E:        return ACCESIO_USB_AI16_32E;
        case ACCESIO_NOFW_USB_AI12_32A:        return ACCESIO_USB_AI12_32A;
        case ACCESIO_NOFW_USB_AI12_32:         return ACCESIO_USB_AI12_32;
        case ACCESIO_NOFW_USB_AI12_32E:        return ACCESIO_USB_AI12_32E;
        case ACCESIO_NOFW_USB_AI16_64A:        return ACCESIO_USB_AI16_64A;
        case ACCESIO_NOFW_USB_AI16_64E:        return ACCESIO_USB_AI16_64E;
        case ACCESIO_NOFW_USB_AI12_64A:        return ACCESIO_USB_AI12_64A;
        case ACCESIO_NOFW_USB_AI12_64:         return ACCESIO_USB_AI12_64;
        case ACCESIO_NOFW_USB_AI12_64E:        return ACCESIO_USB_AI12_64E;
        case ACCESIO_NOFW_USB_AI16_96A:        return ACCESIO_USB_AI16_96A;
        case ACCESIO_NOFW_USB_AI16_96E:        return ACCESIO_USB_AI16_96E;
        case ACCESIO_NOFW_USB_AI12_96A:        return ACCESIO_USB_AI12_96A;
        case ACCESIO_NOFW_USB_AI12_96:         return ACCESIO_USB_AI12_96;
        case ACCESIO_NOFW_USB_AI12_96E:        return ACCESIO_USB_AI12_96E;
        case ACCESIO_NOFW_USB_AI16_128A:       return ACCESIO_USB_AI16_128A;
        case ACCESIO_NOFW_USB_AI16_128E:       return ACCESIO_USB_AI16_128E;
        case ACCESIO_NOFW_USB_AI12_128A:       return ACCESIO_USB_AI12_128A;
        case ACCESIO_NOFW_USB_AI12_128:        return ACCESIO_USB_AI12_128;
        case ACCESIO_NOFW_USB_AI12_128E:       return ACCESIO_USB_AI12_128E;
        case ACCESIO_NOFW_USB_AO_ARB1:         return ACCESIO_USB_AO_ARB1;
        case ACCESIO_NOFW_USB_AO16_16A:        return ACCESIO_USB_AO16_16A;
        case ACCESIO_NOFW_USB_AO16_16:         return ACCESIO_USB_AO16_16;
        case ACCESIO_NOFW_USB_AO16_12A:        return ACCESIO_USB_AO16_12A;
        case ACCESIO_NOFW_USB_AO16_12:         return ACCESIO_USB_AO16_12;
        case ACCESIO_NOFW_USB_AO16_8A:         return ACCESIO_USB_AO16_8A;
        case ACCESIO_NOFW_USB_AO16_8:          return ACCESIO_USB_AO16_8;
        case ACCESIO_NOFW_USB_AO16_4A:         return ACCESIO_USB_AO16_4A;
        case ACCESIO_NOFW_USB_AO16_4:          return ACCESIO_USB_AO16_4;
        case ACCESIO_NOFW_USB_AO12_16A:        return ACCESIO_USB_AO12_16A;
        case ACCESIO_NOFW_USB_AO12_16:         return ACCESIO_USB_AO12_16;
        case ACCESIO_NOFW_USB_AO12_12A:        return ACCESIO_USB_AO12_12A;
        case ACCESIO_NOFW_USB_AO12_12:         return ACCESIO_USB_AO12_12;
        case ACCESIO_NOFW_USB_AO12_8A:         return ACCESIO_USB_AO12_8A;
        case ACCESIO_NOFW_USB_AO12_8:          return ACCESIO_USB_AO12_8;
        case ACCESIO_NOFW_USB_AO12_4A:         return ACCESIO_USB_AO12_4A;
        case ACCESIO_NOFW_USB_AO12_4:          return ACCESIO_USB_AO12_4;
        case ACCESIO_NOFW_USB_AIO16_16A:       return ACCESIO_USB_AIO16_16A;
        case ACCESIO_NOFW_USB_AIO16_16E:       return ACCESIO_USB_AIO16_16E;
        case ACCESIO_NOFW_USB_AIO12_16A:       return ACCESIO_USB_AIO12_16A;
        case ACCESIO_NOFW_USB_AIO12_16:        return ACCESIO_USB_AIO12_16;
        case ACCESIO_NOFW_USB_AIO12_16E:       return ACCESIO_USB_AIO12_16E;
        case ACCESIO_NOFW_USB_AIO16_64MA:      return ACCESIO_USB_AIO16_64MA;
        case ACCESIO_NOFW_USB_AIO16_64ME:      return ACCESIO_USB_AIO16_64ME;
        case ACCESIO_NOFW_USB_AIO12_64MA:      return ACCESIO_USB_AIO12_64MA;
        case ACCESIO_NOFW_USB_AIO12_64M:       return ACCESIO_USB_AIO12_64M;
        case ACCESIO_NOFW_USB_AIO12_64ME:      return ACCESIO_USB_AIO12_64ME;
        case ACCESIO_NOFW_USB_AIO16_32A:       return ACCESIO_USB_AIO16_32A;
        case ACCESIO_NOFW_USB_AIO16_32E:       return ACCESIO_USB_AIO16_32E;
        case ACCESIO_NOFW_USB_AIO12_32A:       return ACCESIO_USB_AIO12_32A;
        case ACCESIO_NOFW_USB_AIO12_32:        return ACCESIO_USB_AIO12_32;
        case ACCESIO_NOFW_USB_AIO12_32E:       return ACCESIO_USB_AIO12_32E;
        case ACCESIO_NOFW_USB_AIO16_64A:       return ACCESIO_USB_AIO16_64A;
        case ACCESIO_NOFW_USB_AIO16_64E:       return ACCESIO_USB_AIO16_64E;
        case ACCESIO_NOFW_USB_AIO12_64A:       return ACCESIO_USB_AIO12_64A;
        case ACCESIO_NOFW_USB_AIO12_64:        return ACCESIO_USB_AIO12_64;
        case ACCESIO_NOFW_USB_AIO12_64E:       return ACCESIO_USB_AIO12_64E;
        case ACCESIO_NOFW_USB_AIO16_96A:       return ACCESIO_USB_AIO16_96A;
        case ACCESIO_NOFW_USB_AIO16_96E:       return ACCESIO_USB_AIO16_96E;
        case ACCESIO_NOFW_USB_AIO12_96A:       return ACCESIO_USB_AIO12_96A;
        case ACCESIO_NOFW_USB_AIO12_96:        return ACCESIO_USB_AIO12_96;
        case ACCESIO_NOFW_USB_AIO12_96E:       return ACCESIO_USB_AIO12_96E;
        case ACCESIO_NOFW_USB_AIO16_128A:      return ACCESIO_USB_AIO16_128A;
        case ACCESIO_NOFW_USB_AIO16_128E:      return ACCESIO_USB_AIO16_128E;
        case ACCESIO_NOFW_USB_AIO12_128A:      return ACCESIO_USB_AIO12_128A;
        case ACCESIO_NOFW_USB_AIO12_128:       return ACCESIO_USB_AIO12_128;
        case ACCESIO_NOFW_USB_AIO12_128E:      return ACCESIO_USB_AIO12_128E;
        case ACCESIO_NOFW_USB_AI16_2A:         return ACCESIO_USB_AI16_2A;
        default: break;
    }
    return id;
}

#endif // ACCESIO_LINUX_IDS_H